[package]
name = "nix2sbom"
version = "0.0.0-placeholder-version"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }

serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
